### ISSUE TITLE
最好能实现自动重启哔哩客户端

### ISSUE THREAD

**Issue by lxfly2000** [xiaoyaocz/BiliAnimeDownload#1]
1.调用客户端下载时貌似必须要强制停止再打开才能看到缓存任务（至少我的是这样），所以我建议是在选择剧集下载后对哔哩哔哩进程killbackgroundprocess然后自动重启。
2.主界面不输入直接点开始读取后会闪退。
3.调用系统下载的（我只试验了魔法使^的新娘1080p）在哔哩客户端里播放视频长度显示0，不能滑动进度条。手动改的话是改index.json中duration改成各分段的毫秒数。

**Comment by wjm2038** [comment]
kill 需要更高权限的吧

**Comment by lxfly2000** [comment]
@wjm2038 是，需要一个“android.permission.KILL_BACKGROUND_PROCESSES”，权限的问题我觉得只要不涉及ROOT，不滥用，能合理使用的该加还是要加上的。
