### ISSUE TITLE
关于自某时刻开始无法解析和下载番剧的问题

### ISSUE THREAD

**Issue by Grand-cocoa** [xiaoyaocz/BiliAnimeDownload#16]
自从某时刻开始，bilibili新放出的番剧均无法解析和下载，但是更早之前放出的番剧依然正常。

**Comment by JockeyWang** [comment]
试着输入sid吧……可能分享页面的地址变了

**Comment by Grand-cocoa** [comment]
也不行，提示API有问题，应该是bilibili后来放出的番剧下载接口变了，Google拓展程序中有一个叫“B站下载助手”，此拓展可以正常下载，希望能够借鉴一下此拓展解决问题
