### ISSUE TITLE
关于Flutter的一些功能建议

### ISSUE THREAD

**Issue by JockeyWang** [xiaoyaocz/BiliAnimeDownload#27]
1、历史记录点击后自动刷新时间，且按时间排序
----这里可以让用户选择是否这么做，或者选择升序降序啥的（我个人的习惯是需要刷新，升序就行）
----对于收藏夹点进去的，是否需要更新历史记录，这个我也说不清，你觉得怎么比较好

2、历史记录和收藏可以在列表中单条删除，比如右滑或者长按菜单之类的

3、收藏夹中点进番剧，返回时回到收藏夹，而不是直接退出程序

4、历史记录清除时，需要确定对话框
----收藏夹也可以考虑提供一键清空的选项，当然也需要确定的

5、搜索时提供一个纯数字的默认选项，个人建议自动补上ss专题（每次手动输入ss还是有点烦的）
----比如左边提供一个下拉框，列出"空,av,ss,md,ep"等支持的类型，这个选项更改后需要自动保存，重启程序后仍然生效

6、下载列表里，如果可以的话，同时显示一下来源于啥
----番剧名称和单集名称都行，现在全是audio.mp4和video.mp4，有时候由于网络波动导致下载失败，都不知道是哪个炸了。

7、下载列表经常出现进度与系统下载进度条不符的情况，这个是啥原理，有点不太理解。（这里我怀疑是个BUG。）

8、打算在github上开源Flutter么？毕竟这个涉及到登陆操作，还是有点小慌的。

**Comment by JockeyWang** [comment]
@xiaoyaocz 你的Flutter还没开源。。我就先在这里提issue了。。

**Comment by xiaoyaocz** [comment]
移步https://github.com/diocz/flutter_bilidown

**Comment by JockeyWang** [comment]
好的……辛苦了
